#!/usr/bin/env node
/**
 * Generates the parser script used by the library
 */
const fs = require('fs');
const Parser = require('jison').Parser;

fs.writeFileSync(
    `${__dirname}/../src/parser.js`,
    new Parser(fs.readFileSync(`${__dirname}/grammar.jison`, 'utf8'))
        .generate()
);
