#!/usr/bin/env node
/**
 * Generates the parser script used by the library
 */
const fs = require('fs');
const Parser = require('jison').Parser;

const source = new Parser(fs.readFileSync(`${__dirname}/grammar.jison`, 'utf8')).generate();

fs.writeFileSync(`${__dirname}/../src/_parser.js`, source);
