// @flow
export default {
    TABLE: 'TABLE',
    BOOLEAN: 'BOOLEAN',
    JOIN: 'JOIN',
    QUERY: 'QUERY',
    QUERY_CALL: 'QUERY_CALL',
    FIELD: 'FIELD',
    RAW_TEXT: 'RAW',
    RAW_TEXT_LONG: 'LRAW',
    OPERATION: 'OPERATION',
    VARIABLE: 'VARIABLE',
    BUILT_IN: 'BUILT_IN',
    MUTATION: 'MUTATION',
    STRING: 'STRING',
    LONG_STRING: 'LONG_STRING'
};
