// @flow
export default {
    TABLE: 'TABLE',
    BOOLEAN: 'BOOLEAN',
    JOIN: 'JOIN',
    QUERY: 'QUERY',
    QUERY_CALL: 'QUERY_CALL',
    FIELD: 'FIELD',
    RAW_TEXT: 'RAW',
    LONG_TEXT: 'LONG_TEXT',
    OPERATION: 'OPERATION',
    VARIABLE: 'VARIABLE',
    BUILT_IN: 'BUILT_IN',
    MUTATION: 'MUTATION'
};
