// flow-typed signature: 9c4fe972c188badaf1f28363c4593b9c
// flow-typed version: <<STUB>>/squel_v5.12.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'squel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'squel' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'squel/dist/squel-basic' {
    declare module.exports: any;
}

declare module 'squel/dist/squel-basic.min' {
    declare module.exports: any;
}

declare module 'squel/dist/squel' {
    declare module.exports: any;
}

declare module 'squel/dist/squel.min' {
    declare module.exports: any;
}

declare module 'squel/gulpfile' {
    declare module.exports: any;
}

// Filename aliases
declare module 'squel/dist/squel-basic.js' {
    declare module.exports: $Exports<'squel/dist/squel-basic'>;
}
declare module 'squel/dist/squel-basic.min.js' {
    declare module.exports: $Exports<'squel/dist/squel-basic.min'>;
}
declare module 'squel/dist/squel.js' {
    declare module.exports: $Exports<'squel/dist/squel'>;
}
declare module 'squel/dist/squel.min.js' {
    declare module.exports: $Exports<'squel/dist/squel.min'>;
}
declare module 'squel/gulpfile.js' {
    declare module.exports: $Exports<'squel/gulpfile'>;
}
